### ISSUE TITLE
ReferenceError: eve is not defined with "raphael-2.2.1.min.js"

### ISSUE THREAD

**Issue by undeflabs** [toorshia/justgage#249]
Just changed `examples/auto-adjust.htm` to `raphael-2.2.1.min.js` results into:

`ReferenceError: eve is not defined`
`eve.on("raphael.anim.start." + (obj.level.id), function() {`

The gauge will be rendered, but the value will not be displayed.
Tested with `justgage/1.2.9`.

**Comment by toorshia** [comment]
Quick search on internet told me people are having similar issue when using Raphael 2.2.X with require.js, ember. I have to investigate further, looks like it's about way eve is declared.

**Comment by toorshia** [comment]
Looks like eve is not exposed anymore, so justgage can't access it any longer :) I recommend sticking with 2.2.0, or fiddling your way through using no-deps version of Raphael and then baking your own eve support. 

Guidelines here:
https://github.com/DmitryBaranovskiy/raphael/issues/524#issuecomment-250844828

**Comment by Steveee79** [comment]
No longer needed since 2.2.4, and the 2.2.7 version has been corrected.
Feel free to upgrade to the 2.2.7 version of Raphael. It Works.

**Comment by D252874** [comment]
why is justgage not automatic having the 2.2.7 version of raphael installed because I am still getting this error

**Comment by D252874** [comment]
2.2.8 is not working and what is the best way to upgrade becouse i got the eve is not defined in justgage files and not in raphael files

**Comment by robertsLando** [comment]
Fixed 81cff4cd1ef3a57df5575421730b67a2aa3207de
