### ISSUE TITLE
Gauge blinking when value is above max.

### ISSUE THREAD

**Issue by Tychus** [toorshia/justgage#272]
![image](https://cloud.githubusercontent.com/assets/1427215/23022766/39882572-f45b-11e6-8e22-18a89d3cc407.png)

once the value goes above 4 the gauge will start switching between 4 and the current value. is there any setting to remove max value or disable this behavior ?

**Comment by woodev01** [comment]
I wrote an issue which I closed about this exact behavior and how I fixed it. 

https://github.com/toorshia/justgage/issues/268

If you can't get it to work let me know.

**Comment by Tychus** [comment]
@woodev01 yup tried that didn't solve it. while i like this in some gauges where things can go beyond the recommended limit in other gauges i don't want it to happen. maybe this can be a parameter or something like that ?

**Comment by woodev01** [comment]
@Tychus - What would you like the other option to be? Should it just show the Max number w/o flickering?

So, let's say you have an 'allowOverflow' flag in your parameters. If true, overflow is allowed without the flicker (a.k.a. the fix in 268) and then, if false, it only shows the Max number if it is overflowed?

**Comment by andrepaulo** [comment]
It also happens when the value is under the min value, when you are refreshing a value, It shows the min value .. then after shows the new value. I'm reporting this here cause I think it's related

**Comment by Tychus** [comment]
@woodev01 i think it'll be a good parameter.

if(blinkOnOverflow == true)
    Gauge value will switch between Max and current value.
else
    Gauge will be full but will only show the value (no max) so it will remain as in the image here all the time
![image](https://cloud.githubusercontent.com/assets/1427215/23089481/18cee20c-f592-11e6-81fa-2992c55bb425.png)
